server:
  port: 8001
debug: false
# DataSource configuration ,springboot auto-configuration
spring:
  application:
    name: epark-pay-service
  datasource:
    url: jdbc:mysql://192.168.1.102:3306/epark?useUnicode=true&characterEncoding=utf8
    username: test
    password: aabbcc2020
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis-config.xml

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

# epark configuration
epark:
  callbackUrl: http://jtss.rzbus.cn:8001
  callbackUrlZfb: http://alipay.ggjtss.cn:8001
  rocketmq:
    nameserver: 192.168.1.213:9876,192.168.1.153:9876

# add mysql log
logging:
  level:
    com.bitcom.base.mapper: debug

